server:
  name: PokeMythic Ranked
  version: 1.1.0
  locale: pt_BR
database:
  type: mysql
  host: 127.0.0.1
  port: 3306
  name: ranked_db
  user: usuario
  pass: senha
  pool:
    maxConnections: 10
    minIdle: 1
    connectionTimeout: 30000
logging:
  level: INFO
  logMatches: true
  logDir: ranked_logs
integrations:
  discord:
    enabled: true
    webhookUrl: ''
    postMatchSummary: true
  payments:
    enabled: false
    provider: mercadopago
extras:
  api:
    enabled: true
    port: 8081
    token: SUA_API_TOKEN
  spectatorMode:
    enable: true
    allowedGroups:
    - STAFF
    - DONO
  autoReportCheat:
    enabled: true
    thresholdSuspicious: 0.9
dbSchema:
  players: ranked_players
  stats: ranked_stats
  matches: ranked_matches
  seasons: ranked_seasons
  bans: ranked_bans
  queues: ranked_queues
  penalties: ranked_penalties
files:
  tiers: tiers.yml
  elos: elos.yml
  bans_global: bans/global_bans.yml
  bans_dir: bans/per_tier/
  commands: commands.yml
  permissions: permissions.yml
  rewards: rewards.yml
  seasons: seasons.yml
  messages: messages.yml
  anti_smurf: anti_smurf.yml
